jobs:
- name: docker
  templates:
  - name: docker
    release: docker
  - name: newrelic-monitor
    release: newrelic
  instances: 2
  resource_pool: default
  persistent_disk_pool: docker-ssd
  networks:
  - name: default
    default:
    - dns
    - gateway


properties:
  collectd:
    riemann_server: ""
  swarm_manager:
    docker_nodes:
    - 0.docker.default.cf-docker-swarm-broker.bosh
    - 1.docker.default.cf-docker-swarm-broker.bosh
