meta:
  environment: cf-docker-swarm-broker
  availability_zone: us-gov-west-1a
  service_secrets:
    elk: secret
    es: secret
    es175: secret
    redis: secret
    mysql: secret
    mongo: secret
    couch: secret

director_uuid: secret

properties:
  newrelic:
    license_key: secret
    deployment_tag: docker-swarm-broker
  nats:
    user: secret
    password: secret
    port: 4222
    machines: [secret]
  cf:
    api_url: https://api.cf.com
    admin_username: user
    admin_password: secret
  broker:
    name: cf-swarm-containers-broker
    host: cf-swarm-containers-broker.cf.com
    username: containers
    password: secret
    cookie_secret: secret
    component_name: cf-swarm-containers-broker
    docker_url: secret

networks:
- name: default
  type: manual
  cloud_properties:
    security_groups:
    - sec_group
    subnet: subnet
  static:
  - <changme>
  gateway: <changeme>
  reserved:
  - <changeme>
  range: <changeme>

jobs:
- name: docker
  networks:
  - name: default
    static_ips:
    - <changeme>
