---
jobs:
- name: deploy-docker-swarm-production
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: docker-swarm-config
      trigger: true
    - get: common-prod
    - get: cg-s3-collectd-release
    - get: docker-swarm-stemcell
  - task: docker-swarm-manifest
    file: pipeline-tasks/spiff-merge.yml
    config:
      inputs:
        - name: pipeline-tasks
        - name: docker-swarm-config
        - name: common-prod
      params:
        OUTPUT_FILE: spiff-merge/manifest.yml
        SOURCE_FILE: docker-swarm-config/docker-swarm.yml
        MERGE_FILES: common-prod/secrets.yml
  - put: docker-swarm-production-deployment
    params:
      cert: common-prod/boshCA.crt
      manifest: spiff-merge/manifest.yml
      releases:
        - cg-s3-collectd-release/collectd*.tgz
      stemcells:
        - docker-swarm-stemcell/*.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy docker-swarm on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed docker-swarm on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}


resources:
- name: common-prod
  type: cg-common
  source:
    bucket_name: {{docker-swarm-private-bucket-production}}
    access_key_id: {{docker-swarm-private-access-key-id-production}}
    secret_access_key: {{docker-swarm-private-secret-access-key-production}}
    secrets_file: docker-swarm.yml
    secrets_passphrase: {{docker-swarm-production-private-passphrase}}
    bosh_cert: bosh.pem

- name: cg-s3-collectd-release
  type: s3
  source:
    access_key_id: {{s3-bosh-releases-access-key-id}}
    bucket: {{s3-bosh-releases-bucket}}
    private: true
    regexp: collectd-(.*).tgz
    secret_access_key: {{s3-bosh-releases-secret-access-key}}

- name: docker-swarm-config
  type: git
  source:
    uri: {{cg-deploy-docker-swarm-git-url}}
    branch: {{cg-deploy-docker-swarm-git-branch}}

- name: docker-swarm-stemcell
  type: bosh-io-stemcell
  source:
    name: {{docker-swarm-stemcell}}

- name: docker-swarm-production-deployment
  type: 18f-bosh-deployment
  source:
    target: {{docker-swarm-production-deployment-bosh-target}}
    username: {{docker-swarm-production-deployment-bosh-username}}
    password: {{docker-swarm-production-deployment-bosh-password}}
    deployment: {{docker-swarm-production-deployment-bosh-deployment}}
    ignore_ssl: false

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
